# @package _global_

defaults:
  - /experiment/fs_ce_distill_abstract


ckpt: ckpt/ce_miniImageNet_resnet10/last.ckpt

eval:
  fine_tune:
    target: "system.bolts.ce_distill_self_paws"

    snn_temp: 0.1
    sharpen_temp: 0.25

    unlabel_aug: "weak_strong"
    # unlabel_linear: "support" # "base"

    no_grad_support: true
