# @package _global_

# fixed backbone
# defaults:
# - /eval/fine_tune/optimizer: SGD
# - override /eval/fine_tune: deep

launcher:
  time: "2"

support_batch_size: 5
support_aug: "few_shot_query"
support_repeat: 1
query_aug: null

eval_mode: "few_shot"
print_val: true

eval:
  fine_tune:
    freeze_bn: false
    last_k: null

    post_train:
      reset_head: true
      freeze_backbone: true
      use_norm: false

    name: "deep"
    trainer_params:
      gpus: 1
      max_epochs: 100
      checkpoint_callback: false
      logger: false
      progress_bar_refresh_rate: 0
      num_sanity_val_steps: 0
      check_val_every_n_epoch: 5
      weights_summary: null
