# @package _global_

defaults:
  - /eval/fine_tune/ft: selftrain
  - /eval/fine_tune/optimizer: SGD
  - /eval/fine_tune/filter: threshold
  - override /eval/fine_tune: deep

data:
  val_dataset: EuroSAT_test
  dataset: EuroSAT_train

eval:
  fine_tune:
    threshold: null
    selection_type: "class"
    unlabel_num_classes: 10

    batch_size: 4
    freeze_bn: false # batchnorm freeze
    last_k: -1 # unfreeze all

    lr_multiplier_backbone: 1.0

    optimizer:
      weight_decay: 0.0

    in_train:
      reset_head: true
      freeze_backbone: false
      use_norm: true

    post_train:
      freeze_backbone: true
      use_norm: true

    pre_train:
      freeze_backbone: false
      use_norm: true
