# @package _global_

defaults:
  - /eval/fine_tune/ft: self_pseudo
  - /eval/fine_tune/optimizer: SGD
  - /eval/fine_tune/filter: threshold
  - override /eval/fine_tune: deep

data:
  val_dataset: EuroSAT_test
  dataset: EuroSAT_train

support_batch_size_fixmatch: 5
support_aug: "few_shot_query"
support_repeat: 1
query_aug: null
support_aug_fixmatch: "few_shot_query"

eval:
  fine_tune:
    target: "system.bolts.fixmatch"
    threshold: 0.5
    selection_type: "class"

    unlabel_aug: "weak_strong"
    temperature: 0.5
    lr_multiplier_backbone: 1.0
    weight_schedule: true

    weight_pos: 1

    unlabel_params:
      batch_size: 32

    optimizer:
      weight_decay: 0

    # NOTE this is what matters
    post_train:
      freeze_backbone: true
      use_norm: true

    in_train:
      reset_head: true
      freeze_backbone: false
      use_norm: true

    pre_train:
      null
      # freeze_backbone: true
      # use_norm: true
