# @package _global_

defaults:
  - /eval/fine_tune/ft: self_pseudo
  - /eval/fine_tune/filter: threshold
  - /eval/fine_tune/optimizer@eval.fine_tune.in_train.optimizer: SGD
  - override /eval/fine_tune: deep

data:
  val_dataset: EuroSAT_test
  dataset: EuroSAT_train

support_batch_size_fixmatch: 25
support_aug: "few_shot_query"
support_repeat: 5
query_aug: null
support_aug_fixmatch: "few_shot_query"

eval:
  fine_tune:
    num_iter: 2

    target: "system.bolts.custom_fixmatch2"
    threshold: 0.5
    # selection_type: "class"

    unlabel_aug: "weak_strong"
    temperature: 1
    lr_multiplier_backbone: 1.0
    weight_schedule: true

    weight_pos: 1
    weight_entropy: 0.5
    weight_tfm: 0.

    unlabel_params:
      batch_size: 32

    tfm_dim: 128

    support_batch_size_in_train: 32
    support_aug: "few_shot_query"
    support_repeat: 10

    in_train:
      reset_head: false
      freeze_backbone: false
      use_norm: true

    pre_train:
      reset_head: true
      freeze_backbone: true
      use_norm: true
